[package]
name = "backend"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown-meta-parser = "0.1.3"
rocket = { version = "0.5.1-rc.1", features = ["secrets", "json", "tls"] }
# Removed rocket_contrib as it's not compatible with Rocket 0.5
serde = { version = "1.0.177", features = ["derive"] }
serde_json = "1.0.104"
bcrypt = "0.17.0"
jsonwebtoken = "9.3.1"
dotenv = "0.15"
walkdir = "2.4.0"
glob = "0.3.1"
lazy_static = "1.4.0"
serde_urlencoded = "0.7.1"
once_cell = "1.21.0"
mio = "1.0.3"
mongodb = "3.2.2"
log = "0.4.26"
chrono = "0.4.40"
tracing = "0.1.41"
reqwest = { version = "0.12.14", features = ["json", "multipart"]}
tokio = { version = "1.44.1", features = ["full"] }
url = "2.5.4"
sha2 = "0.10.8"
hex = "0.4.3"


[build-dependencies]
rocket_codegen = "0.5.1-rc.1"


[profile.dev]
opt-level = 1  # Use minimal optimization to handle _FORTIFY_SOURCE
debug = 1  # Reduced debug info
incremental = false  # Disable incremental compilation to save space

[profile.release]
opt-level = 'z'  # Optimize for size
lto = true
codegen-units = 1
panic = 'abort'
