[default]
secret_key="0NdvRhTPcOIkn1WlKgohcLX98fCuKrPMd+9OSpHQDe8="

# [default.tls]
# certs = ""
# key = ""

[debug]
address = "127.0.0.1"
port = 8000
workers = 4
keep_alive = 5
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 80
workers = 2
keep_alive = 5
limits = { forms = 32768 }